// Copyright (c) 2026 R1GUI. All rights reserved. Proprietary.
// Owns: the unified, ordered window event record delivered by Window::takeEvents().
// Why: the toolkit's input routing needs every key, character, pointer, focus, size, DPI and
//   close event in arrival order in one stream; per-kind queues lose relative ordering.
// Callers: Window.h (producer), ui-core event routing and examples/preview (consumers).
// Invariants: coordinates are client-space physical pixels (float); a field not named by the
//   event type's comment is zero/default. Events are plain values, safe to copy and store.
#pragma once

#include <cstdint>

#include "r1ui/platform/Geometry.h"

namespace r1ui::platform {

enum class MouseButton { Left, Middle, Right, X1, X2 };

struct Modifiers {
  bool ctrl = false;
  bool shift = false;
  bool alt = false;
  bool meta = false;  // Windows / Command key
  friend bool operator==(const Modifiers&, const Modifiers&) = default;
};

enum class EventType : uint8_t {
  KeyDown,           // virtualKey, scanCode, repeat, modifiers
  KeyUp,             // virtualKey, scanCode, modifiers
  Char,              // codePoint (Unicode scalar value, never a control character), modifiers
  MouseDown,         // button, x, y, modifiers
  MouseUp,           // button, x, y, modifiers
  MouseDoubleClick,  // button, x, y, modifiers; always follows the MouseDown of the second click
  MouseMove,         // x, y, modifiers (may be outside the client area while captured)
  MouseLeave,        // the pointer left the window
  Wheel,             // x, y, wheelX, wheelY (notches, fractional for precision devices), modifiers
  FocusGained,
  FocusLost,
  CaptureLost,    // the OS took pointer capture away while buttons were held: cancel any drag
  Resized,        // rect = {0, 0, client width, client height}; 0x0 when minimized
  Moved,          // rect = outer window rectangle in screen physical pixels
  DpiChanged,     // dpiScale = new scale, rect = the suggested rectangle already applied
  CloseRequested  // the user or OS asked the window to close
};

struct Event {
  EventType type = EventType::MouseMove;
  Modifiers modifiers;
  uint32_t virtualKey = 0;  // Windows virtual-key code
  uint32_t scanCode = 0;    // hardware scancode; 0xE000 bits set for extended keys
  bool repeat = false;      // KeyDown generated by auto-repeat
  char32_t codePoint = 0;
  MouseButton button = MouseButton::Left;
  float x = 0.0f;
  float y = 0.0f;
  float wheelX = 0.0f;  // positive = right
  float wheelY = 0.0f;  // positive = away from the user (scroll up)
  float dpiScale = 1.0f;
  Rect rect;
};

}  // namespace r1ui::platform
