# Owns: turning one compiled SPIR-V file into a C++ source with a byte array.
# Why: the renderer embeds its shaders so no runtime file lookup can fail.
# Callers: the custom commands in source/ui-render/CMakeLists.txt (cmake -P).
# Inputs: INPUT (.spv path), OUTPUT (.cpp path), SYMBOL (name declared in vulkan/Shaders.h).
# Invariant: the byte array is 4-byte aligned and its size is a multiple of 4 (SPIR-V words).
file(READ ${INPUT} hex HEX)
string(LENGTH "${hex}" hexLength)
math(EXPR byteCount "${hexLength} / 2")
math(EXPR remainder "${byteCount} % 4")
if(NOT remainder EQUAL 0 OR byteCount EQUAL 0)
  message(FATAL_ERROR "embed_spirv: ${INPUT} is not a whole number of SPIR-V words")
endif()
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n  " bytes "${bytes}")
file(WRITE ${OUTPUT}
"// Generated by embed_spirv.cmake from the shader source; do not edit.
#include \"Shaders.h\"

namespace r1ui::render::detail {
namespace {
alignas(4) const unsigned char kBytes[] = {
  ${bytes}
};
}  // namespace
const ShaderBlob ${SYMBOL}{kBytes, sizeof(kBytes)};
}  // namespace r1ui::render::detail
")
